/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { ExactEvmScheme } from "@x402/evm/exact/client";
import { wrapFetchWithPayment, x402Client } from "@x402/fetch";
import { useCallback, useEffect, useRef, useState } from "react";
import { useConnect, useConnection, useDisconnect, useSwitchChain, useWalletClient } from "wagmi";
import type { CheckoutSnapshot } from "./types";
import { displayPrice, humanize } from "./utils";

const NETWORK = "eip155:84532" as const;
const CHAIN_ID = 84532;
function short(address:string){return `${address.slice(0,6)}…${address.slice(-4)}`}

export function Checkout({ listingId }: { listingId: string }) {
  const [checkout,setCheckout]=useState<CheckoutSnapshot|null>(null),[loadError,setLoadError]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const pollCount=useRef(0);
  const connection=useConnection(),{connectAsync,connectors}=useConnect(),{disconnect}=useDisconnect(),{switchChainAsync}=useSwitchChain(),{data:walletClient}=useWalletClient({chainId:CHAIN_ID});
  const load=useCallback(async()=>{try{const response=await fetch(`/api/purchases/${encodeURIComponent(listingId)}`,{cache:"no-store"});if(!response.ok)throw 0;setCheckout(await response.json());setLoadError(false)}catch{setLoadError(true)}},[listingId]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(checkout?.status!=="settlement_pending"){pollCount.current=0;return}const timer=setInterval(()=>{pollCount.current+=1;if(pollCount.current>=40){clearInterval(timer);setMessage("Receipt reconciliation is taking longer than expected. Reload to check again.");return}void load()},1500);return()=>clearInterval(timer)},[checkout?.status,load]);
  async function connectWallet(){setMessage("");try{const connector=connectors.find(item=>item.type==="injected")??connectors[0];if(!connector)throw 0;await connectAsync({connector})}catch{setMessage("A compatible browser wallet is required to continue.")}}
  async function approve(){if(!checkout||!connection.address)return;setBusy(true);setMessage("");try{if(connection.chainId!==CHAIN_ID)await switchChainAsync({chainId:CHAIN_ID});if(!walletClient)throw new Error("wallet_not_ready");const expected={amount:checkout.amount.atomicAmount,recipient:checkout.recipientAddress.toLowerCase(),asset:checkout.asset.toLowerCase()};const signer={address:connection.address,signTypedData:async(args:{domain:Record<string,unknown>;types:Record<string,unknown>;primaryType:string;message:Record<string,unknown>})=>walletClient.signTypedData({account:connection.address,...args} as never)};const client=new x402Client().register(NETWORK,new ExactEvmScheme(signer)).setSpendControls({maxAmountPerPayment:false}).registerPolicy((version,requirements)=>version===2?requirements.filter(item=>item.scheme==="exact"&&item.network===NETWORK&&item.amount===expected.amount&&item.payTo.toLowerCase()===expected.recipient&&item.asset.toLowerCase()===expected.asset):[]);const response=await wrapFetchWithPayment(fetch,client)(`/api/purchases/${encodeURIComponent(listingId)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({buyerAddress:connection.address,approved:true})});const body=await response.json().catch(()=>null);if(!response.ok&&response.status!==202)throw new Error(body?.error?.message??"Payment could not be completed.");setMessage(response.status===202?"Payment confirmed. Preparing your receipt…":"Purchase complete.");await load()}catch(error){setMessage(error instanceof Error&&error.message!=="wallet_not_ready"?error.message:"Wallet authorization was not completed.")}finally{setBusy(false)}}
  async function reconcile(){setBusy(true);try{const response=await fetch(`/api/purchases/${encodeURIComponent(listingId)}/reconcile`,{method:"POST"});if(!response.ok)throw 0;setMessage("Receipt reconciliation restarted.");await load()}catch{setMessage("Receipt reconciliation is still unavailable. Your settlement reference remains preserved.")}finally{setBusy(false)}}
  if(loadError)return <section className="checkout-panel" aria-labelledby="checkout-title"><h2 id="checkout-title">Purchase</h2><p>Checkout is unavailable right now.</p><button className="button secondary" onClick={load}>Try again</button></section>;
  if(!checkout)return <section className="checkout-panel" aria-busy="true"><div className="skeleton line"/><div className="skeleton line short"/></section>;
  if(checkout.status==="sold"&&checkout.receipt)return <ReceiptView receipt={checkout.receipt}/>;
  return <section className="checkout-panel" aria-labelledby="checkout-title"><div className="checkout-heading"><div><p className="eyebrow">Protected checkout</p><h2 id="checkout-title">Review and purchase</h2></div><span className={`commerce-status ${checkout.status}`}>{humanize(checkout.status)}</span></div><dl className="approval-facts"><div><dt>Listing</dt><dd>{checkout.title}</dd></div><div><dt>Exact total</dt><dd>{displayPrice(checkout.amount)}</dd></div><div><dt>Condition</dt><dd>{humanize(checkout.condition)} · {checkout.conditionSummary}</dd></div><div><dt>Recipient</dt><dd className="mono break">{checkout.recipientAddress}</dd></div><div><dt>Payment network</dt><dd>Base Sepolia · test USDC</dd></div></dl>{checkout.status==="reconciliation_failed"?<button className="button" disabled={busy} onClick={reconcile}>Retry receipt reconciliation</button>:checkout.status==="settlement_pending"?<p className="pending-copy" role="status">Payment settled. We’re durably recording the sold listing and receipt.</p>:connection.status!=="connected"?<button className="button" onClick={connectWallet}>Connect buyer wallet</button>:<div className="wallet-approval"><p>Connected as <span className="mono">{short(connection.address)}</span>{connection.chainId!==CHAIN_ID&&" · switch to Base Sepolia to continue"}</p><div className="button-row"><button className="button" disabled={busy} onClick={approve}>{busy?"Waiting for approval…":`Approve ${displayPrice(checkout.amount)}`}</button><button className="button secondary" onClick={()=>disconnect()}>Disconnect</button></div></div>}<p className="checkout-note">Nothing is authorized until you press approve and confirm the exact terms in your wallet.</p>{message&&<p className="form-message" role="status">{message}</p>}</section>;
}
function ReceiptView({receipt}:{receipt:NonNullable<CheckoutSnapshot["receipt"]>}){return <section className="receipt" aria-labelledby="receipt-title"><div className="receipt-mark" aria-hidden="true">✓</div><p className="eyebrow">Purchase complete</p><h2 id="receipt-title">Settlement receipt</h2><p>{receipt.listingTitle} is sold to {receipt.buyer.displayName}.</p><dl className="approval-facts"><div><dt>Paid</dt><dd>{displayPrice(receipt.amount)}</dd></div><div><dt>Seller</dt><dd>{receipt.seller.displayName}</dd></div><div><dt>Recipient</dt><dd className="mono break">{receipt.recipientAddress}</dd></div><div><dt>Network</dt><dd>Base Sepolia</dd></div><div><dt>Payment reference</dt><dd className="mono break">{receipt.x402PaymentReference}</dd></div><div><dt>Settlement</dt><dd><a href={`https://sepolia.basescan.org/tx/${receipt.settlementTransaction}`} target="_blank" rel="noreferrer" className="mono">View on BaseScan ↗</a></dd></div><div><dt>Settled</dt><dd>{new Date(receipt.settledAt).toLocaleString()}</dd></div></dl></section>}
